# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "master" do |subconfig|
   subconfig.vm.box = "ubuntu/trusty64"
   subconfig.vm.hostname = "master"
   subconfig.vm.network "private_network", ip: "192.168.33.10"
 end

  (1..2).each do |i|
    config.vm.define "minion#{i}" do |subconfig|
      subconfig.vm.box = "ubuntu/trusty64"
      subconfig.vm.hostname = "minion#{i}"
      subconfig.vm.network "private_network", ip: "192.168.33.1#{i}"
    end
  end

 # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
